//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace FutureCore
{
    /**
     * combo数据
     * @author blue
     */
    public class ComboData
    {
        /// <summary>
        /// combo脚本
        /// </summary>
        public string combo;
        /// <summary>
        ///  优先级
        /// </summary>
        public int priority;
        /// <summary>
        /// 扩展帧数，在判定发生帧之后延续有效判定的帧数
        /// </summary>
        public int extendFrame;
        /// <summary>
        /// 判定规则数据列表
        /// </summary>
        public ArrayList ordweList;

        public ComboData()
        {
            ordweList = new ArrayList();
        }
    }
}

